'use strict';
const $=s=>document.querySelector(s), KEY='homeclean-demo-v1', maxURL='https://web.max.ru/327532514';
const items={sofa:'Диваны',armchair:'Кресла',mattress:'Матрасы',chairs:'Стулья'};
let step=0,draft={},lastSaved=null;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4000);}
function records(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v.filter(x=>x&&typeof x.text==='string'&&typeof x.id==='string').slice(-50):[];}catch{return [];}}
function persist(list){try{localStorage.setItem(KEY,JSON.stringify(list.slice(-50)));return true;}catch{toast('Браузер не разрешил сохранение. Текст обращения можно скопировать.');return false;}}
function label(title,id,kind='text',options){const l=node('label',title),el=node(options?'select':kind==='textarea'?'textarea':'input');el.id=id;el.name=id;if(options)options.forEach(t=>el.append(node('option',t)));else if(kind!=='textarea')el.type=kind;el.maxLength=kind==='textarea'?500:80;l.append(el);return [l,el];}
function field(title,id,kind,value,options){const [l,el]=label(title,id,kind,options);$('#step-content').append(l);el.value=value??'';return el;}
function start(selected='sofa'){draft={service:'Химчистка мебели',counts:{sofa:0,armchair:0,mattress:0,chairs:0},fabric:'Не знаю — нужна консультация',condition:'Освежить после использования',date:'',period:'Нужно согласовать',name:'',phone:'',note:''};draft.counts[selected]=1;step=0;lastSaved=null;render();$('#planner').showModal();}
function collect(){if(step===0)for(const key of Object.keys(items))draft.counts[key]=Number($('#'+key).value);if(step===1){draft.fabric=$('#fabric').value;draft.condition=$('#condition').value;draft.note=$('#note').value.trim();}if(step===2)for(const k of ['date','period','name','phone'])draft[k]=$('#'+k).value.trim();}
function error(){if(step===0&&(Object.values(draft.counts).some(n=>!Number.isInteger(n)||n<0||n>100)||Object.values(draft.counts).reduce((a,b)=>a+b,0)<1))return 'Выберите хотя бы один предмет. Количество каждого — от 0 до 100.';if(step===2){if(!/^\d{4}-\d{2}-\d{2}$/.test(draft.date)||draft.date<today())return 'Выберите сегодняшнюю или будущую дату.';if(draft.name.length<2)return 'Укажите имя — хотя бы два символа.';if(!/^\+?[\d\s()\-]+$/.test(draft.phone)||draft.phone.replace(/\D/g,'').length<10||draft.phone.replace(/\D/g,'').length>15)return 'Проверьте телефон: нужно от 10 до 15 цифр.';}return '';}
function message(){return ['Здравствуйте, HomeClean! Хочу обсудить химчистку мебели.',...Object.entries(items).filter(([k])=>draft.counts[k]>0).map(([k,t])=>t+': '+draft.counts[k]+' шт.'),'Материал: '+draft.fabric+'.','Задача: '+draft.condition+'.',draft.note?'Размеры и детали: '+draft.note:'','Желаемая дата: '+draft.date.split('-').reverse().join('.')+', '+draft.period+'.','Контакт: '+draft.name+', '+draft.phone+'.','Подскажите стоимость и возможность выезда.'].filter(Boolean).join('\n');}
function render(){const body=$('#step-content');body.replaceChildren();$('#error').textContent='';document.querySelectorAll('.progress li').forEach((li,i)=>{li.classList.toggle('current',i===step);if(i===step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current');});$('#back').hidden=step===0;$('#next').hidden=false;$('#next').textContent=['Уточнить детали','Указать дату и контакт','Проверить обращение','Сохранить пробное обращение'][step];
if(step===0){body.append(node('h2','Список мебели.'),node('p','Добавьте нужное количество предметов. Ноль означает, что чистка не нужна. Для проверки используйте вымышленные данные.'));for(const [key,title] of Object.entries(items)){const f=field(title+', шт.',key,'number',draft.counts[key]);f.min=0;f.max=100;f.step=1;}}
if(step===1){body.append(node('h2','Что важно учесть?'),node('p','Материал, размеры и характер загрязнений помогут обсудить работу. Цена и результат не рассчитываются автоматически.'));field('Материал','fabric','text',draft.fabric,['Не знаю — нужна консультация','Тканевая обивка','Разные материалы']);field('Основная задача','condition','text',draft.condition,['Освежить после использования','Есть пятна','Есть запах','Несколько задач']);field('Размеры, пятна и другие детали (необязательно)','note','textarea',draft.note);}
if(step===2){body.append(node('h2','Когда вам удобно?'),node('p','Это пожелание к выезду, а не свободное окно. Заявка никуда не отправляется.'));const d=field('Желаемая дата','date','date',draft.date);d.min=today();field('Удобное время','period','text',draft.period,['Нужно согласовать','Первая половина дня','Вторая половина дня']);field('Как к вам обращаться','name','text',draft.name);const p=field('Телефон','phone','tel',draft.phone);p.autocomplete='off';}
if(step===3){body.append(node('h2','Всё в одном обращении.'),node('p','Проверьте текст. Цена и возможность выезда согласуются с компанией. Чтобы отправить обращение, скопируйте его и вставьте в MAX самостоятельно.'),node('div',message(),'summary'));}
$('#planner').scrollTop=0;}
$('#furniture-start').addEventListener('submit',e=>{e.preventDefault();start(document.querySelector('[name=item]:checked').value);});$('#close').addEventListener('click',()=>$('#planner').close());$('#back').addEventListener('click',()=>{collect();step--;render();});
$('#clean-form').addEventListener('submit',e=>{e.preventDefault();collect();const problem=error();if(problem){$('#error').textContent=problem;return;}if(step<3){step++;render();return;}const record={id:crypto.randomUUID(),text:message(),service:draft.service,status:'Новое / демо',at:new Date().toISOString()};if(!persist([...records(),record]))return;lastSaved=record.id;$('#next').hidden=true;$('#back').hidden=true;const result=node('div',undefined,'result-buttons');const copy=node('button','Скопировать текст','primary');copy.type='button';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(record.text);copy.textContent='Скопировано — откройте MAX';toast('Текст скопирован. Отправьте его в MAX самостоятельно.');}catch{toast('Копирование недоступно. Выделите текст обращения вручную.');}});const link=node('a','Открыть MAX компании','secondary');link.href=maxURL;link.target='_blank';link.rel='noopener';const own=node('button','Посмотреть в демо-кабинете','secondary');own.type='button';own.addEventListener('click',()=>{$('#planner').close();openOwner();});result.append(copy,link,own);$('#step-content').append(node('p','Пробное обращение сохранено только в этом браузере. Компания его не получила.'),result);$('#planner').scrollTop=$('#planner').scrollHeight;});
function openOwner(){const box=$('#inbox');box.replaceChildren();const all=records();if(!all.length)box.append(node('p','Пока пусто. Соберите список мебели и сохраните пробное обращение.'));for(const item of [...all].reverse()){const article=node('article',undefined,'inbox-item');article.append(node('span',item.status,'status'),node('h3',item.service),node('p',item.text));for(const [title,status]of [['В работу (демо)','В работе / демо'],['Отменить (демо)','Отменено / демо']]){const b=node('button',title,'secondary');b.type='button';b.addEventListener('click',()=>{const list=records();const current=list.find(x=>x.id===item.id);if(current){current.status=status;if(persist(list))openOwner();}});article.append(b);}box.append(article);}if(!$('#owner').open)$('#owner').showModal();}
$('#owner-open').addEventListener('click',openOwner);$('#owner-footer').addEventListener('click',openOwner);$('#owner-close').addEventListener('click',()=>$('#owner').close());
