'use strict';
(()=>{
const canvas=document.querySelector('#room-canvas'),ctx=canvas.getContext('2d'),dialog=document.querySelector('#brief-dialog');
const colors={sea:['#103e4b','#64a6a6','#e4d4b7'],earth:['#ac5e3d','#c9956a','#e4d4b7'],garden:['#587057','#ac7b95','#e4d4b7']};const names={floor:'Ковёр на полу',wall:'Панно на стене',sea:'Море',earth:'Земля',garden:'Сад',lines:'Линии',arches:'Арки',patch:'Мозаика'};
let state={mode:'floor',color:'sea',pattern:'lines',scale:44,angle:0,x:.55,y:.77},photo=null,drag=null,timer,photoVersion=0;
const art=document.createElement('canvas');art.width=600;art.height=600;
function notify(s){document.querySelector('#status').textContent=s;clearTimeout(timer);timer=setTimeout(()=>document.querySelector('#status').textContent='',4000);}
function makeArt(){const c=art.getContext('2d'),p=colors[state.color];c.clearRect(0,0,600,600);c.save();c.beginPath();c.ellipse(300,300,280,265,0,0,Math.PI*2);c.clip();c.fillStyle=p[2];c.fillRect(0,0,600,600);if(state.pattern==='lines'){for(let i=-3;i<9;i++){c.strokeStyle=p[(i+6)%3];c.lineWidth=70;c.beginPath();c.moveTo(i*95,-20);c.bezierCurveTo(i*95-200,220,i*95+180,370,i*95-30,640);c.stroke();}}else if(state.pattern==='arches'){for(let i=9;i>0;i--){c.fillStyle=p[i%3];c.beginPath();c.ellipse(300,550,i*55,i*65,0,Math.PI,2*Math.PI);c.lineTo(300+i*55,650);c.lineTo(300-i*55,650);c.fill();}}else{for(let y=0;y<6;y++)for(let x=0;x<6;x++){c.fillStyle=p[(x+y*2)%3];c.fillRect(x*100,y*100,100,100);c.fillStyle=p[(x+y*2+1)%3];c.beginPath();c.arc(x*100+50,y*100+50,36,0,Math.PI*2);c.fill();}}
let seed=97;function random(){seed=seed*16807%2147483647;return(seed-1)/2147483646;}for(let i=0;i<19000;i++){const x=random()*600,y=random()*600;c.strokeStyle=random()>.5?'rgba(255,255,255,.17)':'rgba(0,0,0,.13)';c.lineWidth=1;c.beginPath();c.moveTo(x,y);c.lineTo(x+1.5,y+2);c.stroke();}c.restore();}
function cover(img){const ratio=Math.max(1200/img.width,900/img.height),w=img.width*ratio,h=img.height*ratio;ctx.drawImage(img,(1200-w)/2,(900-h)/2,w,h);}
function draw(){ctx.clearRect(0,0,1200,900);if(photo)cover(photo);else{ctx.fillStyle='#f1ece2';ctx.fillRect(0,0,1200,900);ctx.fillStyle='#d4c5aa';ctx.fillRect(0,570,1200,330);ctx.strokeStyle='#bbad94';ctx.lineWidth=2;for(let x=-500;x<1500;x+=140){ctx.beginPath();ctx.moveTo(x+300,570);ctx.lineTo(x,900);ctx.stroke();}ctx.fillStyle='#c0c3b6';ctx.fillRect(220,430,630,170);ctx.fillStyle='#a4aca2';ctx.fillRect(185,480,60,145);ctx.fillRect(835,480,60,145);ctx.fillStyle='#103e4b';ctx.fillRect(245,625,15,40);ctx.fillRect(818,625,15,40);ctx.strokeStyle='#9aa294';ctx.beginPath();ctx.moveTo(530,432);ctx.lineTo(530,595);ctx.stroke();ctx.fillStyle='#d2c1a4';ctx.fillRect(310,435,110,90);ctx.fillStyle='#708476';ctx.fillRect(650,438,90,90);ctx.strokeStyle='#577261';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(1030,595);ctx.lineTo(1015,355);ctx.stroke();for(let i=0;i<6;i++){ctx.fillStyle=i%2?'#577261':'#7e9580';ctx.beginPath();ctx.ellipse(1015+(i%2?25:-25),370+i*29,36,15,i%2?-.6:.6,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#ac9278';ctx.beginPath();ctx.moveTo(985,540);ctx.lineTo(1060,540);ctx.lineTo(1045,630);ctx.lineTo(999,630);ctx.fill();}
const w=1200*state.scale/100,h=w*(state.mode==='floor'?.51:1);ctx.save();ctx.translate(state.x*1200,state.y*900);ctx.rotate(state.angle*Math.PI/180);ctx.shadowColor='rgba(16,40,40,.25)';ctx.shadowBlur=22;ctx.shadowOffsetY=12;ctx.drawImage(art,-w/2,-h/2,w,h);ctx.restore();ctx.fillStyle='rgba(255,253,249,.86)';ctx.fillRect(18,850,505,32);ctx.fillStyle='#103e4b';ctx.font='16px sans-serif';ctx.fillText('Цифровой эскиз / условный масштаб / ULA Арт Студия',30,872);canvas.setAttribute('aria-label',`${names[state.mode]}, ${names[state.color]}, ${names[state.pattern]}. Масштаб ${state.scale} процентов, поворот ${state.angle} градусов. Можно передвигать стрелками.`);}
function update(redrawArt=true){for(const key of ['mode','color','pattern'])document.querySelectorAll(`[data-${key}]`).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[key]===state[key])));document.querySelector('#scale-value').textContent=state.scale+'%';document.querySelector('#angle-value').textContent=state.angle+'°';if(redrawArt)makeArt();draw();}
document.querySelectorAll('[data-mode],[data-color],[data-pattern]').forEach(b=>b.addEventListener('click',()=>{for(const key of ['mode','color','pattern'])if(b.dataset[key]){state[key]=b.dataset[key];if(key==='mode'){state.y=state.mode==='floor'?.77:.26;state.x=.52;}}update();}));
for(const key of ['scale','angle'])document.querySelector('#'+key).addEventListener('input',e=>{state[key]=Number(e.target.value);update(false);});
function reposition(dx,dy){state.x=Math.min(.85,Math.max(.15,state.x+dx));state.y=Math.min(.86,Math.max(.14,state.y+dy));draw();}
const movements={left:[-.025,0],right:[.025,0],up:[0,-.025],down:[0,.025]};document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>reposition(...movements[b.dataset.move])));
canvas.addEventListener('keydown',e=>{const key=e.key.replace('Arrow','').toLowerCase();if(movements[key]){e.preventDefault();reposition(...movements[key]);}});
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,ox:state.x,oy:state.y};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;const r=canvas.getBoundingClientRect();state.x=Math.min(.85,Math.max(.15,drag.ox+(e.clientX-drag.x)/r.width));state.y=Math.min(.86,Math.max(.14,drag.oy+(e.clientY-drag.y)/r.height));draw();});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
document.querySelector('#reset-position').addEventListener('click',()=>{state.x=.52;state.y=state.mode==='floor'?.77:.26;state.scale=44;state.angle=0;document.querySelector('#scale').value=44;document.querySelector('#angle').value=0;update(false);});
document.querySelector('#photo').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){notify('Выбери JPG, PNG или WebP до 10 МБ');e.target.value='';return;}const token=++photoVersion,url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);if(token!==photoVersion)return;if(img.width*img.height>40000000){notify('Фото слишком большое. Уменьши его до 40 мегапикселей.');return;}photo=img;document.querySelector('#scene-label').textContent='ТВОЯ КОМНАТА / ФОТО ТОЛЬКО В БРАУЗЕРЕ';document.querySelector('#remove-photo').hidden=false;draw();};img.onerror=()=>{URL.revokeObjectURL(url);notify('Не получилось прочитать фото. Попробуй другое.');};img.src=url;});
document.querySelector('#remove-photo').addEventListener('click',()=>{photoVersion++;photo=null;document.querySelector('#photo').value='';document.querySelector('#remove-photo').hidden=true;document.querySelector('#scene-label').textContent='СХЕМАТИЧНЫЙ ИНТЕРЬЕР';draw();});
function brief(){const extra=document.querySelector('#note').value.trim();return `Здравствуйте, Ульяна! Собрал направление в демонстрационной примерочной ULA.\nИнтересует: ${names[state.mode]}.\nПалитра: ${names[state.color]}. Рисунок: ${names[state.pattern]}.\nМасштаб на картинке условный, реальные размеры ещё нужно уточнить.\n${extra?`Пожелания: ${extra}\n`:''}Хотел бы обсудить индивидуальный эскиз, стоимость и сроки. Картинку приложу отдельно.`;}
document.querySelector('#prepare').addEventListener('click',()=>{document.querySelector('#brief').value=brief();document.querySelector('#copy').textContent='Скопировать описание';dialog.showModal();});document.querySelector('#note').addEventListener('input',()=>document.querySelector('#brief').value=brief());document.querySelector('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.querySelector('#brief').value);document.querySelector('#copy').textContent='Описание скопировано';}catch{document.querySelector('#brief').focus();document.querySelector('#brief').select();document.querySelector('#copy').textContent='Выделено — скопируй вручную';}});
document.querySelector('#save-scene').addEventListener('click',()=>canvas.toBlob(blob=>{if(!blob){notify('Не удалось сохранить. Попробуй снова.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ula-interior-concept.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);notify('Картинка подготовлена для скачивания');},'image/png'));
update();
})();
