'use strict';
const $=s=>document.querySelector(s), KEY='ecodom-demo-v1', maxURL='https://web.max.ru/352801215';
const types=['Генеральная уборка','Поддерживающая уборка','После ремонта','Мойка окон'];
let step=0,draft={},lastSaved=null,chosenDay='Среда';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4000);}
function records(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v.filter(x=>x&&typeof x.text==='string'&&typeof x.id==='string').slice(-50):[];}catch{return [];}}
function persist(list){try{localStorage.setItem(KEY,JSON.stringify(list.slice(-50)));return true;}catch{toast('Браузер не разрешил сохранение. Текст обращения можно скопировать.');return false;}}
function label(title,id,kind='text',options){const l=node('label',title),el=node(options?'select':kind==='textarea'?'textarea':'input');el.id=id;el.name=id;if(options)options.forEach(t=>el.append(node('option',t)));else if(kind!=='textarea')el.type=kind;el.maxLength=kind==='textarea'?500:80;l.append(el);return [l,el];}
function field(title,id,kind,value,options){const [l,el]=label(title,id,kind,options);$('#step-content').append(l);el.value=value??'';return el;}
function start(service=types[0]){draft={place:'Квартира',area:'',service,extras:[],date:'',period:'Нужно согласовать',name:'',phone:'',note:'',town:'Екатеринбург',frequency:$('#frequency').value,weekday:chosenDay};step=0;lastSaved=null;render();$('#planner').showModal();}
function collect(){if(step===0){draft.town=$('#town').value;draft.frequency=$('#draft-frequency').value;draft.weekday=$('#draft-day').value;draft.place=$('#place').value;draft.area=$('#area').value.trim();}if(step===1){draft.service=$('#service').value;draft.extras=[...document.querySelectorAll('[name=extra]:checked')].map(el=>el.value);draft.note=$('#note').value.trim();}if(step===2){for(const k of ['date','period','name','phone'])draft[k]=$('#'+k).value.trim();}}
function error(){if(step===0&&(!Number.isFinite(Number(draft.area))||Number(draft.area)<=0||Number(draft.area)>10000))return 'Укажите площадь от 1 до 10 000 м².';if(step===2){if(!/^\d{4}-\d{2}-\d{2}$/.test(draft.date)||draft.date<today())return 'Выберите сегодняшнюю или будущую дату.';if(draft.name.length<2)return 'Укажите имя — хотя бы два символа.';if(!/^\+?[\d\s()\-]+$/.test(draft.phone)||draft.phone.replace(/\D/g,'').length<10||draft.phone.replace(/\D/g,'').length>15)return 'Проверьте телефон: нужно от 10 до 15 цифр.';}return '';}
function message(){return ['Здравствуйте, ЭКО ДОМ! Хочу уточнить уборку.','Город: '+draft.town+'.','Желаемый ритм: '+draft.frequency+' / '+draft.weekday+'.','Помещение: '+draft.place+', '+draft.area+' м².','Формат: '+draft.service+'.','Дополнительно: '+(draft.extras.join(', ')||'без отдельных пожеланий')+'.','Желаемая дата: '+draft.date.split('-').reverse().join('.')+', '+draft.period+'.',draft.note?'Комментарий: '+draft.note:'','Контакт: '+draft.name+', '+draft.phone+'.','Подскажите стоимость, состав работ и возможность выезда.'].filter(Boolean).join('\n');}
function render(){const body=$('#step-content');body.replaceChildren();$('#error').textContent='';document.querySelectorAll('.progress li').forEach((li,i)=>{li.classList.toggle('current',i===step);if(i===step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current');});$('#back').hidden=step===0;$('#next').hidden=false;$('#next').textContent=['Выбрать работы','Указать дату и контакт','Проверить обращение','Сохранить пробное обращение'][step];
if(step===0){body.append(node('h2','Что будем убирать?'),node('p','Для проверки используйте вымышленные данные. Точный адрес здесь не нужен.'));field('Город','town','text',draft.town,['Екатеринбург','Косулино','Арамиль','Берёзовский','Заречный','Сысерть']);field('Частота (пожелание)','draft-frequency','text',draft.frequency,['Разовый визит','Раз в неделю','Раз в две недели','Обсудить другой график']);field('День недели (пожелание)','draft-day','text',draft.weekday,['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье']);field('Помещение','place','text',draft.place,['Квартира','Дом','Офис']);const a=field('Площадь, м²','area','number',draft.area);a.min=1;a.max=10000;a.inputMode='decimal';}
if(step===1){body.append(node('h2','Выберите задачи.'),node('p','Отметьте пожелания для обсуждения. Их состав и стоимость менеджер подтвердит отдельно.'));field('Формат уборки','service','text',draft.service,types);for(const text of ['Мойка окон','Уборка внутри шкафов']){const l=node('label',undefined,'check'),cb=node('input');cb.type='checkbox';cb.name='extra';cb.value=text;cb.checked=draft.extras.includes(text);l.append(cb,node('span',text));body.append(l);}field('Что важно учесть (необязательно)','note','textarea',draft.note);}
if(step===2){body.append(node('h2','Когда вам удобно?'),node('p','Это пожелание к выезду, а не свободное окно. Заявка никуда не отправляется.'));const d=field('Желаемая дата','date','date',draft.date);d.min=today();field('Удобное время','period','text',draft.period,['Нужно согласовать','Первая половина дня','Вторая половина дня']);field('Как к вам обращаться','name','text',draft.name);const p=field('Телефон','phone','tel',draft.phone);p.autocomplete='off';}
if(step===3){body.append(node('h2','Всё в одном обращении.'),node('p','Проверьте текст. Цена и возможность выезда согласуются с компанией. Чтобы отправить обращение, скопируйте его и вставьте в MAX самостоятельно.'),node('div',message(),'summary'));}
$('#planner').scrollTop=0;}
$('#rhythm-form').addEventListener('submit',e=>{e.preventDefault();start($('#frequency').value==='Разовый визит'?types[0]:'Поддерживающая уборка');});document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.service)));$('#close').addEventListener('click',()=>$('#planner').close());$('#back').addEventListener('click',()=>{collect();step--;render();});
$('#clean-form').addEventListener('submit',e=>{e.preventDefault();collect();const problem=error();if(problem){$('#error').textContent=problem;return;}if(step<3){step++;render();return;}const record={id:crypto.randomUUID(),text:message(),service:draft.service,status:'Новое / демо',at:new Date().toISOString()};if(!persist([...records(),record]))return;lastSaved=record.id;$('#next').hidden=true;$('#back').hidden=true;const result=node('div',undefined,'result-buttons');const copy=node('button','Скопировать текст','primary');copy.type='button';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(record.text);copy.textContent='Скопировано — откройте MAX';toast('Текст скопирован. Отправьте его в MAX самостоятельно.');}catch{toast('Копирование недоступно. Выделите текст обращения вручную.');}});const link=node('a','Открыть MAX компании','secondary');link.href=maxURL;link.target='_blank';link.rel='noopener';const own=node('button','Посмотреть в демо-кабинете','secondary');own.type='button';own.addEventListener('click',()=>{$('#planner').close();openOwner();});result.append(copy,link,own);$('#step-content').append(node('p','Пробное обращение сохранено только в этом браузере. Компания его не получила.'),result);$('#planner').scrollTop=$('#planner').scrollHeight;});
function openOwner(){const box=$('#inbox');box.replaceChildren();const all=records();if(!all.length)box.append(node('p','Пока пусто. Составьте план уборки и сохраните пробное обращение.'));for(const item of [...all].reverse()){const article=node('article',undefined,'inbox-item');article.append(node('span',item.status,'status'),node('h3',item.service),node('p',item.text));for(const [title,status]of [['В работу (демо)','В работе / демо'],['Отменить (демо)','Отменено / демо']]){const b=node('button',title,'secondary');b.type='button';b.addEventListener('click',()=>{const list=records();const current=list.find(x=>x.id===item.id);if(current){current.status=status;if(persist(list))openOwner();}});article.append(b);}box.append(article);}if(!$('#owner').open)$('#owner').showModal();}
$('#owner-open').addEventListener('click',openOwner);$('#owner-footer').addEventListener('click',openOwner);$('#owner-close').addEventListener('click',()=>$('#owner').close());

function showRhythm(){ $('#rhythm-preview').textContent=$('#frequency').value+' / '+chosenDay; }
$('#frequency').addEventListener('change',showRhythm);
document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>{chosenDay=b.dataset.day;document.querySelectorAll('[data-day]').forEach(v=>v.setAttribute('aria-pressed',String(v===b)));showRhythm();}));
