'use strict';
(() => {
  const palettes={terra:['#d56035','#e9d6b0','#52342a'],olive:['#747b3e','#e9d6b0','#323d2c'],berry:['#9c324e','#eec2bd','#492b42'],ink:['#394868','#e5ded0','#282f43']};
  const labels={flower:'Цветок',cloud:'Облако',circle:'Круг',terra:'Терракота',olive:'Олива',berry:'Ягода',ink:'Чернила',sun:'Солнце',waves:'Волны',checker:'Шахматы'};
  const defaults={shape:'flower',palette:'terra',pattern:'sun',size:'80'};
  let state={...defaults};
  try { const saved=JSON.parse(localStorage.getItem('matyr-design-v1')); if(saved && ['flower','cloud','circle'].includes(saved.shape)&&palettes[saved.palette]&&['sun','waves','checker'].includes(saved.pattern)&&['45','80','90'].includes(saved.size)) state={shape:saved.shape,palette:saved.palette,pattern:saved.pattern,size:saved.size}; } catch{}
  const canvas=document.querySelector('#rug'),hero=document.querySelector('#hero-rug'),dialog=document.querySelector('#brief-dialog');
  let toastTimer,frame;
  function notify(text){const el=document.querySelector('#status');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4000);}
  function boundary(a,shape){if(shape==='circle')return 315;if(shape==='flower')return 285+50*Math.cos(7*a);return 295+35*Math.sin(3*a+.7)+22*Math.cos(5*a);}
  function colorAt(x,y,p,colors){const r=Math.hypot(x,y);if(p==='sun')return r<112?colors[1]:(r<129?colors[2]:colors[0]);if(p==='waves')return colors[((Math.floor((x+55*Math.sin(y/80)+500)/105)%3)+3)%3];return ((Math.floor((x+450)/100)+Math.floor((y+450)/100))%2)?colors[0]:colors[1];}
  function draw(target,s){const ctx=target.getContext('2d');ctx.clearRect(0,0,900,900);const colors=palettes[s.palette];ctx.save();ctx.translate(450,450);ctx.beginPath();for(let i=0;i<=560;i++){let a=i/560*Math.PI*2;let r=boundary(a,s.shape);if(i===0)ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);else ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fillStyle=colors[2];ctx.fill();ctx.strokeStyle=colors[2];ctx.lineWidth=8;ctx.stroke();
    // A deterministic yarn-loop illustration, not a photograph of a studio product.
    let seed=127;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};
    for(let y=-370;y<=370;y+=4.4){for(let x=-370;x<=370;x+=4.4){let px=x+(random()-.5)*3,py=y+(random()-.5)*3;const r=Math.hypot(px,py),edge=boundary(Math.atan2(py,px),s.shape);if(r>edge-2)continue;const c=colorAt(px,py,s.pattern,colors);ctx.strokeStyle=c;ctx.lineWidth=4.3;ctx.beginPath();ctx.moveTo(px-1,py+2);ctx.quadraticCurveTo(px+random()*3,py-3.5,px+2,py);ctx.stroke();ctx.strokeStyle=random()>.55?'rgba(255,253,249,.22)':'rgba(30,15,5,.19)';ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(px-1,py+1);ctx.quadraticCurveTo(px,py-3,px+1,py-1);ctx.stroke();}}
    ctx.restore();target.setAttribute('aria-label',`Эскиз: ${labels[s.shape]}, палитра ${labels[s.palette]}, рисунок ${labels[s.pattern]}`);
  }
  function render(){document.querySelectorAll('[data-shape],[data-palette],[data-pattern]').forEach(button=>{for(const key of ['shape','palette','pattern'])if(button.dataset[key])button.setAttribute('aria-pressed',String(button.dataset[key]===state[key]));});document.querySelector('#size').value=state.size;document.querySelector('#ruler-size').textContent=`${state.size} см`;document.querySelector('#preview-caption').textContent=`${labels[state.shape]} / ${labels[state.palette]} / ${labels[state.pattern]}`;const id=1+['flower','cloud','circle'].indexOf(state.shape)*12+Object.keys(palettes).indexOf(state.palette)*3+['sun','waves','checker'].indexOf(state.pattern);document.querySelector('#design-id').textContent=String(id).padStart(3,'0');cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{draw(canvas,state);draw(hero,state);});try{localStorage.setItem('matyr-design-v1',JSON.stringify(state));}catch{}}
  document.querySelectorAll('[data-shape],[data-palette],[data-pattern]').forEach(button=>button.addEventListener('click',()=>{for(const key of ['shape','palette','pattern'])if(button.dataset[key])state[key]=button.dataset[key];render();}));
  document.querySelector('#size').addEventListener('change',e=>{state.size=e.target.value;render();});
  document.querySelector('#reset').addEventListener('click',()=>{state={...defaults};render();notify('Вернул первоначальный эскиз');});
  function brief(){return `Здравствуйте! Собрал идею ковра в демонстрационном конструкторе.\nФорма: ${labels[state.shape]}.\nПалитра: ${labels[state.palette]}. Рисунок: ${labels[state.pattern]}.\nПримерный размер: ${state.size} × ${state.size} см.\nПодскажите, можно ли сделать такой ковёр на мастер-классе или на заказ? Хотел бы уточнить стоимость и сроки. Эскиз приложу отдельно.`;}
  document.querySelector('#prepare').addEventListener('click',()=>{document.querySelector('#brief').value=brief();document.querySelector('#copy').textContent='Скопировать описание';dialog.showModal();});
  document.querySelector('#copy').addEventListener('click',async()=>{const text=document.querySelector('#brief').value;try{await navigator.clipboard.writeText(text);document.querySelector('#copy').textContent='Описание скопировано';}catch{document.querySelector('#brief').focus();document.querySelector('#brief').select();document.querySelector('#copy').textContent='Выделено — скопируй вручную';}});
  document.querySelector('#download').addEventListener('click',()=>{const out=document.createElement('canvas');out.width=1100;out.height=1250;const ctx=out.getContext('2d');ctx.fillStyle='#fffdf9';ctx.fillRect(0,0,1100,1250);ctx.fillStyle='#34251f';ctx.font='34px sans-serif';ctx.fillText('МАТУР-КОВЁР / МОЯ ИДЕЯ',65,85);ctx.drawImage(canvas,100,100,900,900);ctx.font='28px sans-serif';ctx.fillText(`${labels[state.shape]} / ${labels[state.palette]} / ${labels[state.pattern]}`,65,1050);ctx.font='24px sans-serif';ctx.fillText(`Желаемый размер: ${state.size} × ${state.size} см`,65,1100);ctx.font='19px sans-serif';ctx.fillText('Цифровой эскиз. Не заказ и не фотография готового изделия.',65,1170);out.toBlob(blob=>{if(!blob){notify('Не удалось сохранить. Попробуй ещё раз.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`matyr-${state.shape}-${state.palette}-${state.size}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);notify('Эскиз подготовлен для скачивания');},'image/png');});
  dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
  render();
})();
