import{available,validateContact}from'./booking.mjs';
const KEY='remboks-app-demo-v1',initial=[['tires','Шиномонтаж',60,'Смена шин, ремонт порезов и ошиповка.'],['discs','Правка дисков',90,'Правка, прокатка и сварка дисков.'],['alignment','Развал-схождение',60,'Проверка углов установки колёс.'],['oil','Замена масла',60,'В том числе аппаратная замена.'],['diagnostics','Диагностика',60,'Компьютерная диагностика автомобиля.'],['climate','Климатическая система',90,'Обслуживание климатической системы.']].map(([id,name,duration,description])=>({id,name,duration,description,price:''}));
let state={services:structuredClone(initial),visits:[]},storageOK=true;try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&Array.isArray(v.services)&&Array.isArray(v.visits)&&v.services.length===6)state=v;}catch{storageOK=false;}
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=(n=0)=>{const d=new Date();d.setDate(d.getDate()+n);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const dateText=d=>new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'}),price=s=>s.price?`${Number(s.price).toLocaleString('ru-RU')} ₽ / демо`:'Цена у мастера';
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;return true;}catch{storageOK=false;return false;}}
function notify(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4200);}
function view(id){if(!['home','services','visits','contacts','owner'].includes(id))id='home';document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('.bottom-nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.view===id?'page':'false'));render();window.scrollTo(0,0);}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));$('.brand').addEventListener('click',e=>{e.preventDefault();view('home');});
function message(v){return`Здравствуйте! Хочу согласовать визит в РемБокс. Услуга: ${v.serviceName}. Желаемое время: ${dateText(v.date)}, ${v.time}. Автомобиль: ${v.car}. Имя: ${v.name}. Телефон: ${v.phone}. Подтвердите, пожалуйста, время и стоимость. Это запрос, не подтверждённая запись.`;}
function visitHTML(v,owner=false){return`<article class="visit"><span class="status">${v.status==='cancelled'?'Отменена / демо':v.status==='confirmed'?'Подтверждена в демо':'Ожидает / демо'}</span><h3>${esc(v.serviceName)}</h3><p>${dateText(v.date)}, ${esc(v.time)} / ${v.duration} мин. условно<br>${esc(v.car)} / ${esc(v.name)}</p>${owner?`<p>${esc(v.phone)}</p>`:''}${v.status!=='cancelled'?`${owner&&v.status==='pending'?`<button class="secondary" data-confirm="${v.id}">Подтвердить в демо</button> `:''}<button class="secondary" data-cancel="${v.id}">Отменить пробную запись</button>`:''}${!owner?`<div><button class="secondary" data-copy="${v.id}">Скопировать обращение</button><a href="https://t.me/+79122406228" target="_blank" rel="noopener">Открыть Telegram мастера</a></div>`:''}</article>`;}
function render(){
$('#service-list').innerHTML=state.services.map((s,i)=>`<article class="service-row"><span class="service-number">0${i+1}</span><div><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p></div><button data-service="${s.id}">Выбрать <small>${price(s)}</small></button></article>`).join('');
$('#visit-list').innerHTML=state.visits.length?state.visits.slice().reverse().map(v=>visitHTML(v)).join(''):'<p class="empty">Пока пусто. Выберите услугу и пройдите пробную запись.</p><button class="primary" data-book>Попробовать запись</button>';
const day=$('#owner-date').value||localDate(1);$('#owner-date').value=day;const visits=state.visits.filter(v=>v.date===day).sort((a,b)=>a.time.localeCompare(b.time));$('#schedule-list').innerHTML=visits.length?visits.map(v=>visitHTML(v,true)).join(''):'<p class="empty">На эту дату пробных записей нет.</p>';
$('#settings-list').innerHTML=state.services.map(s=>`<div class="setting"><span>${esc(s.name)}</span><label>Демо-цена, ₽<input name="price-${s.id}" type="number" min="0" max="1000000" step="1" value="${esc(s.price)}" placeholder="Уточняется"></label><label>Демо-длительность<select name="duration-${s.id}">${[30,60,90,120,180].map(n=>`<option value="${n}" ${s.duration===n?'selected':''}>${n} мин.</option>`).join('')}</select></label></div>`).join('');
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-book'))openBooking();if(b.dataset.service)openBooking(b.dataset.service);if(b.dataset.cancel||b.dataset.confirm){const v=state.visits.find(x=>x.id===(b.dataset.cancel||b.dataset.confirm));if(v){v.status=b.dataset.cancel?'cancelled':'confirmed';save();render();notify('Статус изменён в демонстрации');}}if(b.dataset.copy){const v=state.visits.find(x=>x.id===b.dataset.copy);try{await navigator.clipboard.writeText(message(v));notify('Текст скопирован. Вставьте его в чат мастеру.');}catch{notify('Не удалось скопировать. Разрешите буфер обмена в браузере.');}}});
$('#owner-date').addEventListener('change',render);for(const mode of['schedule','settings'])$('#show-'+mode).addEventListener('click',()=>{for(const x of['schedule','settings']){$('#'+x).hidden=x!==mode;$('#show-'+x).setAttribute('aria-pressed',String(x===mode));}});
$('#settings').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.services=state.services.map(s=>({...s,price:f.get('price-'+s.id),duration:Number(f.get('duration-'+s.id))}));$('#settings-status').textContent=save()?'Сохранено в этом браузере. Клиентский экран обновлён.':'Хранилище недоступно: изменения действуют до перезагрузки.';render();});
let step=0,draft={},opener;const dialog=$('#booking');
function openBooking(id){opener=document.activeElement;step=id?1:0;draft={serviceId:id||state.services[0].id,date:localDate(1),time:'',name:'',phone:'',car:''};renderStep();dialog.showModal();}
$('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>opener?.focus());$('#back-step').addEventListener('click',()=>{if(step>0){capture();step--;renderStep();}});
function service(){return state.services.find(s=>s.id===draft.serviceId);}
function capture(){if(step===2){for(const k of['name','phone','car'])draft[k]=$('#field-'+k).value.trim();}}
function renderStep(){const s=service();$('#form-error').textContent='';$('#step-count').textContent=`Шаг ${step+1} из 4`;document.querySelectorAll('.progress i').forEach((x,i)=>x.classList.toggle('active',i<=step));$('#step-title').textContent=['ВЫБЕРИТЕ РАБОТЫ','ПРИМЕРЬТЕ ВРЕМЯ','ВАШ АВТОМОБИЛЬ','ПРОВЕРЬТЕ ДЕТАЛИ'][step];$('#back-step').hidden=step===0;$('#next-step').textContent=['Выбрать время','Указать автомобиль','Проверить детали','Создать пробную запись'][step];
if(step===0)$('#step-body').innerHTML=`<div class="choices">${state.services.map(x=>`<button class="choice" type="button" data-pick="${x.id}" aria-pressed="${x.id===draft.serviceId}"><span>${esc(x.name)}</span><small>${price(x)}</small></button>`).join('')}</div>`;
if(step===1){$('#step-body').innerHTML=`<label>Желаемая дата<input id="booking-date" type="date" min="${localDate()}" max="${localDate(30)}" value="${draft.date}" required></label><p class="demo-warning">Учебное расписание 09:00–20:00, один бокс. Длительность ${s.duration} мин. условная. Это не свободные окна реального сервиса.</p><div class="slots" id="slots"></div>`;drawSlots();$('#booking-date').addEventListener('change',e=>{draft.date=e.target.value;draft.time='';drawSlots();});}
if(step===2)$('#step-body').innerHTML=`<p class="demo-warning">Для проверки используйте вымышленные данные. Они останутся только на вашем устройстве.</p><label>Как к вам обращаться<input id="field-name" required minlength="2" maxlength="70" autocomplete="off" value="${esc(draft.name)}" placeholder="Например, Тест"></label><label>Телефон<input id="field-phone" required type="tel" maxlength="20" autocomplete="off" value="${esc(draft.phone)}" placeholder="Номер для демонстрации"></label><label>Автомобиль<input id="field-car" required minlength="2" maxlength="90" value="${esc(draft.car)}" placeholder="Марка и модель"></label>`;
if(step===3)$('#step-body').innerHTML=`<dl class="summary"><div><dt>Работы</dt><dd>${esc(s.name)}</dd></div><div><dt>Дата</dt><dd>${dateText(draft.date)}, ${draft.time}</dd></div><div><dt>Автомобиль</dt><dd>${esc(draft.car)}</dd></div><div><dt>Контакт</dt><dd>${esc(draft.name)}<br>${esc(draft.phone)}</dd></div><div><dt>Стоимость</dt><dd>${price(s)}</dd></div></dl><p class="demo-warning">После нажатия запись появится в демо-кабинете на этом устройстве. Мастер её не получит. Для реального визита отправьте обращение в Telegram или позвоните.</p>`;
}
function drawSlots(){const s=service();$('#slots').innerHTML=Array.from({length:22},(_,i)=>`${String(9+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`).map(t=>`<button type="button" class="slot" data-time="${t}" aria-pressed="${draft.time===t}" ${available(draft.date,t,s.duration,state.visits)?'':'disabled'}>${t}</button>`).join('');}
$('#step-body').addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.pick){draft.serviceId=b.dataset.pick;draft.time='';renderStep();}if(b?.dataset.time){draft.time=b.dataset.time;drawSlots();}});
$('#booking-form').addEventListener('submit',e=>{e.preventDefault();capture();const s=service();if(step===1&&(!draft.time||!available(draft.date,draft.time,s.duration,state.visits))){$('#form-error').textContent='Выберите доступное время в демонстрационном расписании.';return;}if(step===2&&!validateContact(draft.name,draft.phone,draft.car)){$('#form-error').textContent='Укажите имя, автомобиль и телефон из 10–15 цифр.';return;}if(step<3){step++;renderStep();return;}
// Re-read shared local state to avoid stale reservations in another tab of this same browser.
try{const fresh=JSON.parse(localStorage.getItem(KEY));if(fresh?.visits)state.visits=fresh.visits;}catch{}
if(!available(draft.date,draft.time,s.duration,state.visits)){$('#form-error').textContent='Это время уже занято в демо. Вернитесь и выберите другое.';return;}
state.visits.push({...draft,id:crypto.randomUUID(),serviceName:s.name,duration:s.duration,price:s.price,status:'pending'});const saved=save();$('#owner-date').value=draft.date;dialog.close();view('visits');notify(saved?'Пробная запись создана. Она видна в демо-кабинете.':'Создано только в памяти: хранилище браузера недоступно.');});
window.addEventListener('storage',e=>{if(e.key===KEY){try{const v=JSON.parse(e.newValue);if(v?.visits&&v?.services){state=v;render();}}catch{}}});
render();if(!storageOK)notify('Хранилище недоступно. Демо работает до перезагрузки.');
